# Generated by Django 5.1.15 on 2026-08-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_orderitem_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=255, verbose_name="cancel reason"),
        ),
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=255, verbose_name="cancel reason"),
        ),
    ]
