# Generated by Django 5.1.15 on 2026-07-12 00:15

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSaleOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('channel', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('shop', 'Shop'), ('wholesale', 'Wholesale')], default='shop', max_length=16, verbose_name='channel')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=16, verbose_name='status')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Set automatically when the sale is confirmed.', max_digits=12, verbose_name='total')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, help_text='Leave empty for a walk-in sale.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sale order',
                'verbose_name_plural': 'historical sale orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('shop', 'Shop'), ('wholesale', 'Wholesale')], default='shop', max_length=16, verbose_name='channel')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=16, verbose_name='status')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Set automatically when the sale is confirmed.', max_digits=12, verbose_name='total')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('client', models.ForeignKey(blank=True, help_text='Leave empty for a walk-in sale.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='clients.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'sale order',
                'verbose_name_plural': 'sale orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='unit price')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.productvariant', verbose_name='product variant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleorder', verbose_name='sale order')),
            ],
            options={
                'verbose_name': 'sale item',
                'verbose_name_plural': 'sale items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], default='cash', max_length=16, verbose_name='method')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.saleorder', verbose_name='sale order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], default='cash', max_length=16, verbose_name='method')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder', verbose_name='sale order')),
            ],
            options={
                'verbose_name': 'historical payment',
                'verbose_name_plural': 'historical payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
