# Generated by Django 5.1.15 on 2026-07-12 19:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Pending'), ('confirmed', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Set automatically when the sale is approved.', max_digits=12, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Pending'), ('confirmed', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Set automatically when the sale is approved.', max_digits=12, verbose_name='total'),
        ),
    ]
