# Generated by Django 5.1.15 on 2026-07-13 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_historicalsaleorder_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='reversed_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Set automatically when this row voids an earlier payment.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.payment', verbose_name='reverses payment'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='reviewed'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reviewed at'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_payment',
            field=models.ForeignKey(blank=True, help_text='Set automatically when this row voids an earlier payment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='sales.payment', verbose_name='reverses payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='reviewed'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reviewed at'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', max_length=3, verbose_name='currency'),
        ),
    ]
