# Generated by Django 5.1.15 on 2026-07-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_historicalpayment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mbank', 'MBank'), ('transfer', 'Transfer'), ('other', 'Other')], default='cash', max_length=16, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mbank', 'MBank'), ('transfer', 'Transfer'), ('other', 'Other')], default='cash', max_length=16, verbose_name='method'),
        ),
    ]
