# Generated by Django 5.1.15 on 2026-07-16 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_marketing_consent_client_telegram_chat_id_and_more'),
        ('inventory', '0004_stockmovement_inventory_s_variant_183f66_idx_and_more'),
        ('sales', '0004_alter_historicalpayment_method_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', 'created_at'], name='sales_payme_client__ef0e88_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['status', 'confirmed_at'], name='sales_saleo_status_17786c_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('reversed_payment__isnull', False), _connector='OR'), name='payment_amount_positive_unless_reversal'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='saleitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleorder',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='saleorder_total_nonneg'),
        ),
    ]
