# Generated by Django 5.1.15 on 2026-07-16 23:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_payment_sales_payme_client__ef0e88_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='rate_to_kgs',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='rate to KGS'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='rate_to_kgs',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='rate to KGS'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='total_kgs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total, KGS'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_to_kgs',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='rate to KGS'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='rate_to_kgs',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='rate to KGS'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='total_kgs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total, KGS'),
        ),
    ]
