# Generated by Django 5.1.15 on 2026-07-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_thumbnail'),
        ('sales', '0007_backfill_kgs_snapshots'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['variant'], name='sales_salei_variant_e0a8ab_idx'),
        ),
    ]
