# Generated by Django 5.1.15 on 2026-07-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleitem_sales_salei_variant_e0a8ab_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='rate_official',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='official rate'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='rate_source',
            field=models.CharField(choices=[('nbkr', 'NBKR'), ('manual', 'Manual')], default='nbkr', max_length=16, verbose_name='rate source'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_official',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='official rate'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_source',
            field=models.CharField(choices=[('nbkr', 'NBKR'), ('manual', 'Manual')], default='nbkr', max_length=16, verbose_name='rate source'),
        ),
    ]
