# Generated by Django 5.1.15 on 2026-07-26 18:00

import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_marketing_consent_client_telegram_chat_id_and_more'),
        ('sales', '0009_historicalpayment_rate_official_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='change amount'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='change_amount_kgs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='change amount, KGS'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='change_currency',
            field=models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', max_length=3, verbose_name='change currency'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='change_rounding_kgs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='change rounding residue, KGS'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='excess_disposition',
            field=models.CharField(choices=[('none', '—'), ('change', 'Сдача'), ('debt', 'В счёт долга'), ('credit', 'Аванс')], default='none', max_length=16, verbose_name='excess disposition'),
        ),
        migrations.AddField(
            model_name='payment',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='change amount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='change_amount_kgs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='change amount, KGS'),
        ),
        migrations.AddField(
            model_name='payment',
            name='change_currency',
            field=models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', max_length=3, verbose_name='change currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='change_rounding_kgs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='change rounding residue, KGS'),
        ),
        migrations.AddField(
            model_name='payment',
            name='excess_disposition',
            field=models.CharField(choices=[('none', '—'), ('change', 'Сдача'), ('debt', 'В счёт долга'), ('credit', 'Аванс')], default='none', max_length=16, verbose_name='excess disposition'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('change_amount__gte', 0), ('reversed_payment__isnull', False), _connector='OR'), name='payment_change_amount_nonneg_unless_reversal'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('change_amount_kgs__lte', django.db.models.expressions.CombinedExpression(models.F('amount'), '*', models.F('rate_to_kgs'))), ('reversed_payment__isnull', False), _connector='OR'), name='payment_change_kgs_lte_amount_kgs_unless_reversal'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('change_rounding_kgs__gte', 0), ('change_rounding_kgs__lte', 100)), ('reversed_payment__isnull', False), _connector='OR'), name='payment_change_rounding_bounded_unless_reversal'),
        ),
    ]
