# Generated by Django 5.1.15 on 2026-07-26 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('sales', '0010_historicalpayment_change_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='production_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order', verbose_name='production order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='orders.order', verbose_name='production order'),
        ),
    ]
