# Generated by Django 5.1.15 on 2026-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_historicalpayment_production_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='rate_source',
            field=models.CharField(choices=[('nbkr', 'NBKR'), ('manual', 'Manual'), ('frankfurter', 'Frankfurter')], default='nbkr', max_length=16, verbose_name='rate source'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rate_source',
            field=models.CharField(choices=[('nbkr', 'NBKR'), ('manual', 'Manual'), ('frankfurter', 'Frankfurter')], default='nbkr', max_length=16, verbose_name='rate source'),
        ),
    ]
