# Generated by Django 5.1.15 on 2026-08-02 00:01

import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_alter_productimage_position"),
        ("sales", "0012_frankfurter_rate_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("none", "No discount"),
                    ("percent", "Percent"),
                    ("fixed", "Fixed amount"),
                ],
                default="none",
                max_length=10,
                verbose_name="discount type",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="discount value"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gte", 0)),
                name="saleitem_discount_value_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("discount_type", "percent"), _negated=True),
                    ("discount_value__lte", 100),
                    _connector="OR",
                ),
                name="saleitem_discount_percent_max_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("discount_type", "fixed"), _negated=True),
                    (
                        "discount_value__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("unit_price"), "*", models.F("quantity")
                        ),
                    ),
                    _connector="OR",
                ),
                name="saleitem_discount_fixed_lte_subtotal",
            ),
        ),
    ]
