# Generated by Django 5.1.15 on 2026-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_payment_payment_one_reversal_per_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleorder',
            name='pending_token',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='pending creation token'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='pending_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='pending creation token'),
        ),
    ]
