# Generated by Django 5.1.15 on 2026-08-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productimage_position'),
        ('sales', '0015_historicalsaleorder_pending_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='cost price at sale'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='saleitem_cost_price_nonneg'),
        ),
    ]
