# Generated by Django 5.1.15 on 2026-08-03 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_last_name_to_descriptor'),
        ('orders', '0001_initial'),
        ('sales', '0017_backfill_saleitem_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('order__isnull', False), ('production_order__isnull', False), ('reversed_payment__isnull', False), _connector='OR'), name='payment_must_be_linked_to_order_or_deposit'),
        ),
    ]
