# Generated by Django 5.1.15 on 2026-08-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_payment_payment_must_be_linked_to_order_or_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='batch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='batch'),
        ),
    ]
