# Generated by Django 5.1.15 on 2026-08-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_historicalpayment_batch_id_payment_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleorder',
            name='is_historical',
            field=models.BooleanField(default=False, verbose_name='historical sale'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='is_historical',
            field=models.BooleanField(default=False, verbose_name='historical sale'),
        ),
    ]
