# Generated by Django 5.1.15 on 2026-07-16 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_client_marketing_consent_client_telegram_chat_id_and_more'),
        ('inventory', '0003_historicalproductvariant_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('text_ru', models.TextField(verbose_name='message (Russian)')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=16, verbose_name='channel')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=16, verbose_name='status')),
                ('only_bought_before', models.BooleanField(default=False, verbose_name='only clients who bought before')),
                ('only_with_debt', models.BooleanField(default=False, verbose_name='only clients with debt')),
                ('lapsed_days', models.PositiveIntegerField(blank=True, help_text="Leave empty to ignore. E.g. 60 = haven't purchased in 60 days.", null=True, verbose_name='only clients inactive for N days')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('products', models.ManyToManyField(blank=True, help_text='Their photos are sent as a media group with the message.', to='inventory.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16, verbose_name='status')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign', verbose_name='campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'campaign recipient',
                'verbose_name_plural': 'campaign recipients',
                'constraints': [models.UniqueConstraint(fields=('campaign', 'client'), name='uniq_recipient_per_campaign')],
            },
        ),
    ]
