# Generated by Django 5.1.15 on 2026-07-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('inventory', '0005_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='only_favourited_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product', verbose_name='only clients who favourited this product'),
        ),
    ]
