# Generated by Django 5.1.15 on 2026-07-26 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_client_bot_language_client_human_handoff_until_and_more'),
        ('inventory', '0005_product_thumbnail'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='key')),
                ('title_ru', models.CharField(max_length=200, verbose_name='title (Russian)')),
                ('body_ru', models.TextField(verbose_name='body (Russian)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'bot content',
                'verbose_name_plural': 'bot content',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='new', max_length=16, verbose_name='status')),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=16, verbose_name='source')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('raw_message', models.TextField(blank=True, help_text="The client's own words — kept for a WhatsApp free-text заявка.", verbose_name='raw message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='handled at')),
                ('decline_reason', models.CharField(blank=True, max_length=255, verbose_name='decline reason')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requests', to='clients.client', verbose_name='client')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='handled by')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order request',
                'verbose_name_plural': 'order requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inbox.orderrequest', verbose_name='request')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'request item',
                'verbose_name_plural': 'request items',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='notified at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='clients.client', verbose_name='client')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'stock alert',
                'verbose_name_plural': 'stock alerts',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='clients.client', verbose_name='client')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'favourite',
                'verbose_name_plural': 'favourites',
                'constraints': [models.UniqueConstraint(fields=('client', 'variant'), name='uniq_favourite_per_client')],
            },
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['client', 'status'], name='inbox_order_client__6a255d_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.UniqueConstraint(condition=models.Q(('notified_at__isnull', True)), fields=('client', 'variant'), name='uniq_open_stock_alert_per_client'),
        ),
    ]
