# Generated by Django 5.1.15 on 2026-07-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='receives_reports',
            field=models.BooleanField(default=False, verbose_name='receives daily reports'),
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=16, verbose_name='channel')),
                ('external_id', models.CharField(help_text='Telegram user ID or WhatsApp phone number', max_length=64, verbose_name='external ID')),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=3, verbose_name='direction')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'bot message',
                'verbose_name_plural': 'bot messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'external_id'], name='core_botmes_channel_8be70d_idx')],
            },
        ),
    ]
