# Generated by Django 5.1.15 on 2026-07-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botuser_receives_reports_botmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('date', models.DateField(verbose_name='date')),
                ('rate', models.DecimalField(decimal_places=6, help_text='How many units of the base currency equal 1 unit of this currency.', max_digits=14, verbose_name='rate')),
            ],
            options={
                'verbose_name': 'exchange rate',
                'verbose_name_plural': 'exchange rates',
                'ordering': ['-date', 'currency'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'date'), name='uniq_rate_per_currency_date')],
            },
        ),
    ]
