# Generated by Django 5.1.15 on 2026-07-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('nbkr', 'NBKR')], default='manual', max_length=16, verbose_name='source'),
        ),
    ]
