# Generated by Django 5.1.15 on 2026-07-23 23:27
#
# Rates become one-row-per-currency (the current rate, refreshed on demand)
# instead of a dated row per fetch. Collapse any existing dated duplicates to
# the most recent row per currency before adding the unique(currency) index.

from django.db import migrations, models


def collapse_to_latest_per_currency(apps, schema_editor):
    ExchangeRate = apps.get_model("core", "ExchangeRate")
    seen = set()
    for row in ExchangeRate.objects.order_by("currency", "-date", "-id"):
        if row.currency in seen:
            row.delete()  # keep only the first (newest) row per currency
        else:
            seen.add(row.currency)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exchangerate_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['currency'], 'verbose_name': 'exchange rate', 'verbose_name_plural': 'exchange rates'},
        ),
        migrations.RemoveConstraint(
            model_name='exchangerate',
            name='uniq_rate_per_currency_date',
        ),
        migrations.RunPython(collapse_to_latest_per_currency, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(max_length=3, unique=True, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(help_text='When this rate was last updated.', verbose_name='updated'),
        ),
    ]
