# Generated by Django 5.1.15 on 2026-07-26 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_exchangerate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('old_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='old rate')),
                ('new_rate', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='new rate')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('nbkr', 'NBKR')], max_length=16, verbose_name='source')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='changed at')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Empty for the automatic scheduled/system refresh.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
            ],
            options={
                'verbose_name': 'rate change',
                'verbose_name_plural': 'rate change log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
