# Generated by Django 5.1.15 on 2026-07-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_bot_language_client_human_handoff_until_and_more'),
        ('core', '0006_ratechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_messages', to='clients.client', verbose_name='client'),
        ),
        migrations.AddIndex(
            model_name='botmessage',
            index=models.Index(fields=['client', 'created_at'], name='core_botmes_client__64accd_idx'),
        ),
    ]
