# Generated by Django 5.1.15 on 2026-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_botmessage_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('nbkr', 'NBKR'), ('frankfurter', 'Frankfurter')], default='manual', max_length=16, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='ratechangelog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('nbkr', 'NBKR'), ('frankfurter', 'Frankfurter')], max_length=16, verbose_name='source'),
        ),
    ]
