# Generated by Django 5.1.15 on 2026-08-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_revoke_wildcard_business_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('auth_failure', 'Failed login'), ('forbidden', 'Forbidden (403)'), ('rate_limited', 'Rate limited (429)'), ('receipt_access', 'Receipt accessed')], max_length=20, verbose_name='type')),
                ('ip', models.GenericIPAddressField(verbose_name='IP address')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='path')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'security event',
                'verbose_name_plural': 'security events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_securi_event_t_e93b36_idx'), models.Index(fields=['ip', 'created_at'], name='core_securi_ip_d80f3a_idx')],
            },
        ),
    ]
