# Generated by Django 5.1.15 on 2026-07-12 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
    ]
