# Generated by Django 5.1.15 on 2026-07-12 00:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('photo', models.TextField(blank=True, max_length=100, verbose_name='photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.category', verbose_name='category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, upload_to='products/', verbose_name='photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductVariant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, verbose_name='SKU')),
                ('size', models.CharField(blank=True, max_length=32, verbose_name='size')),
                ('color', models.CharField(blank=True, max_length=64, verbose_name='color')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cost price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='sale price')),
                ('low_stock_threshold', models.PositiveIntegerField(default=2, verbose_name='low stock threshold')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'historical product variant',
                'verbose_name_plural': 'historical product variants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('size', models.CharField(blank=True, max_length=32, verbose_name='size')),
                ('color', models.CharField(blank=True, max_length=64, verbose_name='color')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cost price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='sale price')),
                ('low_stock_threshold', models.PositiveIntegerField(default=2, verbose_name='low stock threshold')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='inventory.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ['product__name', 'size', 'color'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('production_in', 'Production intake'), ('purchase_in', 'Purchase intake'), ('return_in', 'Return'), ('sale_out', 'Sale'), ('writeoff_out', 'Write-off'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='type')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
