# Generated by Django 5.1.15 on 2026-07-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductvariant',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', help_text='Applies to both cost price and sale price.', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', help_text='Applies to both cost price and sale price.', max_length=3, verbose_name='currency'),
        ),
    ]
