# Generated by Django 5.1.15 on 2026-07-16 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_historicalproductvariant_currency_and_more'),
        ('sales', '0004_alter_historicalpayment_method_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['variant', 'created_at'], name='inventory_s_variant_183f66_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stockmovement_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ('production_in', 'purchase_in', 'return_in')), _negated=True), ('quantity__gt', 0), _connector='OR'), name='stockmovement_intake_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ('sale_out', 'writeoff_out')), _negated=True), ('quantity__lt', 0), _connector='OR'), name='stockmovement_outgoing_negative'),
        ),
    ]
