# Generated by Django 5.1.15 on 2026-07-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_inventory_s_variant_183f66_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='products/thumbs/', verbose_name='thumbnail'),
        ),
    ]
