# Product photo -> product gallery (ProductImage, many per product).
#
# Order matters and differs from what `makemigrations` generated by default:
# CreateModel + the data backfill run FIRST, while Product.photo/thumbnail
# still exist to read from; RemoveField runs LAST. Migrating a project with
# real uploaded photos (this one has at least one) with the fields dropped
# first would silently lose that data — there'd be nothing left to copy.

import django.db.models.deletion
from django.db import migrations, models


def copy_photos_into_the_gallery(apps, schema_editor):
    """Every Product with a `photo` gets a ProductImage(position=0) — the
    file itself isn't touched (no re-read, no re-encode): FileField columns
    just store a path string, so copying `.name` onto the new row points it
    at the exact same file on disk/storage. A `thumbnail` already on the
    product carries over the same way; if the product predates thumbnails
    somehow, ProductImage.save() derives one on first save, same as before."""
    Product = apps.get_model("inventory", "Product")
    ProductImage = apps.get_model("inventory", "ProductImage")
    for product in Product.objects.exclude(photo="").exclude(photo__isnull=True):
        ProductImage.objects.create(
            product_id=product.pk,
            image=product.photo.name,
            thumbnail=product.thumbnail.name if product.thumbnail else "",
            position=0,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_product_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="products/", verbose_name="image")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        upload_to="products/thumbs/",
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text=(
                            "Lower numbers show first. The first image is the cover "
                            "shown in tiles."
                        ),
                        verbose_name="position",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="uploaded at")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
                "ordering": ["position", "id"],
            },
        ),
        migrations.RunPython(
            copy_photos_into_the_gallery,
            # Irreversible on purpose: reversing RemoveField below re-adds the
            # column but cannot un-delete the data it held — there is nothing
            # a reverse RunPython could restore that RemoveField hasn't
            # already lost. Nothing in the deploy runbook reverse-migrates.
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="product",
            name="thumbnail",
        ),
    ]
