# Generated by Django 5.1.15 on 2026-08-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
    ]
