# Generated by Django 5.1.15 on 2026-08-07 22:01

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[apps.inventory.models.validate_product_image], verbose_name='image'),
        ),
    ]
