# Generated by Django 5.1.15 on 2026-08-17 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_cost_price_always_kgs"),
        ("sales", "0020_historicalsaleorder_is_historical_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="cost (сом)"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost__isnull", True), ("cost__gte", 0), _connector="OR"),
                name="stockmovement_cost_nonneg",
            ),
        ),
    ]
