# Generated by Django 5.1.15 on 2026-08-17 02:24

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0010_stockmovement_cost"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("contact", models.CharField(blank=True, max_length=200, verbose_name="contact")),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "contractor",
                "verbose_name_plural": "contractors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContractor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("contact", models.CharField(blank=True, max_length=200, verbose_name="contact")),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="created at"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contractor",
                "verbose_name_plural": "historical contractors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProductionRun",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "accepted_qty",
                    models.PositiveIntegerField(default=0, verbose_name="accepted quantity"),
                ),
                (
                    "defect_qty",
                    models.PositiveIntegerField(default=0, verbose_name="defect quantity"),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="note")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="created at"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="manufacturing.contractor",
                        verbose_name="contractor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.orderitem",
                        verbose_name="order item",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.productvariant",
                        verbose_name="product variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical production run",
                "verbose_name_plural": "historical production runs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProductionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "accepted_qty",
                    models.PositiveIntegerField(default=0, verbose_name="accepted quantity"),
                ),
                (
                    "defect_qty",
                    models.PositiveIntegerField(default=0, verbose_name="defect quantity"),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="manufacturing.contractor",
                        verbose_name="contractor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_runs",
                        to="orders.orderitem",
                        verbose_name="order item",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_runs",
                        to="inventory.productvariant",
                        verbose_name="product variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "production run",
                "verbose_name_plural": "production runs",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalExpense",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fabric", "Ткань"),
                            ("trim", "Фурнитура"),
                            ("labor", "Зарплата"),
                            ("rent", "Аренда"),
                            ("other", "Прочее"),
                        ],
                        max_length=10,
                        verbose_name="category",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KGS", "Kyrgyzstani som"),
                            ("USD", "US dollar"),
                            ("RUB", "Russian ruble"),
                        ],
                        default="KGS",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "rate_to_kgs",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, verbose_name="rate to KGS"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="note")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="created at"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="manufacturing.contractor",
                        verbose_name="contractor / supplier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.productvariant",
                        verbose_name="product variant",
                    ),
                ),
                (
                    "production_run",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="manufacturing.productionrun",
                        verbose_name="production run",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical expense",
                "verbose_name_plural": "historical expenses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContractorTransaction",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("accrual", "Accrual (owed for labor)"),
                            ("payment", "Payment (cash handed over)"),
                        ],
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KGS", "Kyrgyzstani som"),
                            ("USD", "US dollar"),
                            ("RUB", "Russian ruble"),
                        ],
                        default="KGS",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "rate_to_kgs",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, verbose_name="rate to KGS"
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="note")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="created at"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="manufacturing.contractor",
                        verbose_name="contractor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "production_run",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="manufacturing.productionrun",
                        verbose_name="production run",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contractor transaction",
                "verbose_name_plural": "historical contractor transactions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fabric", "Ткань"),
                            ("trim", "Фурнитура"),
                            ("labor", "Зарплата"),
                            ("rent", "Аренда"),
                            ("other", "Прочее"),
                        ],
                        max_length=10,
                        verbose_name="category",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KGS", "Kyrgyzstani som"),
                            ("USD", "US dollar"),
                            ("RUB", "Russian ruble"),
                        ],
                        default="KGS",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "rate_to_kgs",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, verbose_name="rate to KGS"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="manufacturing.contractor",
                        verbose_name="contractor / supplier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="inventory.productvariant",
                        verbose_name="product variant",
                    ),
                ),
                (
                    "production_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="manufacturing.productionrun",
                        verbose_name="production run",
                    ),
                ),
            ],
            options={
                "verbose_name": "expense",
                "verbose_name_plural": "expenses",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractorTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("accrual", "Accrual (owed for labor)"),
                            ("payment", "Payment (cash handed over)"),
                        ],
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KGS", "Kyrgyzstani som"),
                            ("USD", "US dollar"),
                            ("RUB", "Russian ruble"),
                        ],
                        default="KGS",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "rate_to_kgs",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, verbose_name="rate to KGS"
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="manufacturing.contractor",
                        verbose_name="contractor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "production_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contractor_transactions",
                        to="manufacturing.productionrun",
                        verbose_name="production run",
                    ),
                ),
            ],
            options={
                "verbose_name": "contractor transaction",
                "verbose_name_plural": "contractor transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productionrun",
            index=models.Index(
                fields=["contractor", "date"], name="manufacturi_contrac_f5aa8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionrun",
            index=models.Index(fields=["variant", "date"], name="manufacturi_variant_89e4fb_idx"),
        ),
        migrations.AddConstraint(
            model_name="productionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("accepted_qty__gte", 0),
                    ("defect_qty__gte", 0),
                    models.Q(("accepted_qty__gt", 0), ("defect_qty__gt", 0), _connector="OR"),
                ),
                name="productionrun_qty_nonzero",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["category", "date"], name="manufacturi_categor_11e689_idx"),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="expense_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate_to_kgs__gt", 0)), name="expense_rate_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="contractortransaction",
            index=models.Index(
                fields=["contractor", "date"], name="manufacturi_contrac_da684b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractortransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ctxn_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractortransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate_to_kgs__gt", 0)), name="ctxn_rate_positive"
            ),
        ),
    ]
