"""A base-currency row can only ever have rate_to_kgs = 1 — 1 сом IS 1 сом.

Enforced at the DB from here on. The rows this repairs first are real: the
/panel/ add form used to expose rate_to_kgs as a REQUIRED, hand-typed field
(no model default + not in the admin's readonly_fields), so a сом expense
filed with the сом-per-dollar rate typed in (88) was stored as amount × 88 —
181 000 сом counted as 15 928 000 in every Расходы total.

Unlike 0009_cost_price_always_kgs in apps.inventory, this repair involves no
approximation and no lost information: the correct rate for a base-currency
row is 1 by definition, so the original amount is recovered exactly. Foreign-
currency rows are NEVER touched here — their correct rate depends on the date
they were filed, which this migration cannot know; `manage.py audit_expenses`
reports those for a human to resolve.

Logged loudly so the count is visible at deploy time, same convention as
0009_cost_price_always_kgs and 0017_backfill_saleitem_cost_price.
"""

import logging

# Generated by Django 5.1.15 on 2026-08-23 01:42

from django.conf import settings
from django.db import migrations, models



logger = logging.getLogger(__name__)


def reset_base_currency_rates(apps, schema_editor):
    from django.conf import settings
    from decimal import Decimal

    repaired = {}
    for model_name in ("Expense", "ContractorTransaction"):
        model = apps.get_model("manufacturing", model_name)
        bad = list(
            model.objects.filter(currency=settings.CURRENCY).exclude(rate_to_kgs=Decimal("1"))
        )
        # Snapshot the OLD rate before mutating — logging it afterwards would
        # record the 1 we just wrote, losing the only record of what the row
        # actually held (and of how far off its total had been).
        repaired[model_name] = [(r.pk, str(r.amount), str(r.rate_to_kgs)) for r in bad]
        for row in bad:
            row.rate_to_kgs = Decimal("1")
            row.save(update_fields=["rate_to_kgs"])

    total = sum(len(v) for v in repaired.values())
    if total:
        logger.warning(
            "base_currency_rate_is_one: reset rate_to_kgs to 1 on %s %s-currency "
            "row(s) that carried a hand-typed rate (pk, amount, old_rate): %s",
            total,
            settings.CURRENCY,
            repaired,
        )
    else:
        logger.info("base_currency_rate_is_one: no mis-rated base-currency rows found.")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockmovement_cost'),
        ('manufacturing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(reset_base_currency_rates, noop_reverse),
        migrations.AddConstraint(
            model_name='contractortransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', 'KGS'), _negated=True), ('rate_to_kgs', 1), _connector='OR'), name='ctxn_base_currency_rate_is_one'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', 'KGS'), _negated=True), ('rate_to_kgs', 1), _connector='OR'), name='expense_base_currency_rate_is_one'),
        ),
    ]
