# Generated by Django 5.1.15 on 2026-07-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('shop', 'Shop'), ('wholesale', 'Wholesale')], max_length=16, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='source',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('shop', 'Shop'), ('wholesale', 'Wholesale')], max_length=16, verbose_name='source'),
        ),
    ]
