# Generated by Django 5.1.15 on 2026-07-16 03:29, hand-edited to preserve
# existing `name` data by splitting it into first_name/last_name before the
# old field is dropped, instead of Django's default lossy remove-then-add.

from django.db import migrations, models


def split_name(apps, schema_editor):
    for model_name in ("Client", "HistoricalClient"):
        model = apps.get_model("clients", model_name)
        for row in model.objects.all():
            first, _, rest = row.name.partition(" ")
            row.first_name = first
            row.last_name = rest
            row.save(update_fields=["first_name", "last_name"])


def join_name(apps, schema_editor):
    for model_name in ("Client", "HistoricalClient"):
        model = apps.get_model("clients", model_name)
        for row in model.objects.all():
            row.name = f"{row.first_name} {row.last_name}".strip()
            row.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client_source_historicalclient_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "client",
                "verbose_name_plural": "clients",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="last name"),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="last name"),
        ),
        migrations.RunPython(split_name, join_name),
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalclient",
            name="name",
        ),
    ]
