# Generated by Django 5.1.15 on 2026-07-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_remove_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='marketing consent'),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='whatsapp_opted_in',
            field=models.BooleanField(default=False, verbose_name='WhatsApp opt-in'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='marketing consent'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='whatsapp_opted_in',
            field=models.BooleanField(default=False, verbose_name='WhatsApp opt-in'),
        ),
    ]
