# Generated by Django 5.1.15 on 2026-07-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_marketing_consent_client_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bot_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызча')], default='ru', max_length=4, verbose_name='bot language'),
        ),
        migrations.AddField(
            model_name='client',
            name='human_handoff_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='human handoff until'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='bot_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызча')], default='ru', max_length=4, verbose_name='bot language'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='human_handoff_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='human handoff until'),
        ),
    ]
