# Generated by Django 5.1.15 on 2026-08-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_historicalclientopeningbalance_clientopeningbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='do_not_remind',
            field=models.BooleanField(default=False, verbose_name='do not remind'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='do_not_remind',
            field=models.BooleanField(default=False, verbose_name='do not remind'),
        ),
    ]
