# Generated by Django 5.1.15 on 2026-08-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_historicalhistoricalpurchase_historicalpurchase'),
    ]

    operations = [
        # DeleteModel alone drops the whole table, constraints included — no
        # need to strip fields first. The autodetector's own RemoveField
        # ops (for client/created_by) ran into their own generated
        # UniqueConstraint still referencing "client" mid-removal, an
        # ordering bug in the autodetector for this exact combination
        # (a model with both FK fields and a multi-field UniqueConstraint
        # being deleted in one migration) — removed here rather than
        # reordered, since they're redundant with DeleteModel anyway.
        migrations.DeleteModel(
            name='HistoricalHistoricalPurchase',
        ),
        migrations.DeleteModel(
            name='HistoricalPurchase',
        ),
    ]
