# Generated by Django 5.1.15 on 2026-07-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_historicalpayment_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReview',
            fields=[
            ],
            options={
                'verbose_name': 'payment review',
                'verbose_name_plural': 'payment review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.payment',),
        ),
    ]
