# Generated by Django 5.1.15 on 2026-08-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReview',
        ),
    ]
