# Generated by Django 5.1.15 on 2026-08-23 22:53

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersonalExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', max_length=3, verbose_name='currency')),
                ('rate_to_kgs', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='rate to KGS')),
                ('tag', models.CharField(choices=[('food', 'Еда'), ('housing', 'Жильё'), ('transport', 'Транспорт'), ('education', 'Образование'), ('health', 'Здоровье'), ('shopping', 'Покупки'), ('entertainment', 'Развлечения'), ('subscriptions', 'Подписки'), ('personal', 'Личное'), ('business', 'Бизнес'), ('fees', 'Комиссии')], max_length=16, verbose_name='tag')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical personal expense',
                'verbose_name_plural': 'historical personal expenses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(choices=[('KGS', 'Kyrgyzstani som'), ('USD', 'US dollar'), ('RUB', 'Russian ruble')], default='KGS', max_length=3, verbose_name='currency')),
                ('rate_to_kgs', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='rate to KGS')),
                ('tag', models.CharField(choices=[('food', 'Еда'), ('housing', 'Жильё'), ('transport', 'Транспорт'), ('education', 'Образование'), ('health', 'Здоровье'), ('shopping', 'Покупки'), ('entertainment', 'Развлечения'), ('subscriptions', 'Подписки'), ('personal', 'Личное'), ('business', 'Бизнес'), ('fees', 'Комиссии')], max_length=16, verbose_name='tag')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'personal expense',
                'verbose_name_plural': 'personal expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tag', 'date'], name='personal_pe_tag_035ee2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='personal_expense_amount_positive'), models.CheckConstraint(condition=models.Q(('rate_to_kgs__gt', 0)), name='personal_expense_rate_positive'), models.CheckConstraint(condition=models.Q(models.Q(('currency', 'KGS'), _negated=True), ('rate_to_kgs', 1), _connector='OR'), name='personal_expense_base_currency_rate_is_one')],
            },
        ),
    ]
